### ISSUE TITLE
Support Deno 1.2.0 and later

### ISSUE THREAD

**Issue by asos-craigmorten** [ako-deno/type_is#2]
Please consider upgrading the dependencies of this repository so consumers can use it for Deno versions greater than ^1.2.0

Errors seen (Deno version 1.4.0):

```console
error: TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { FormatInputPathObject } from "./_interface.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.60.0/path/_util.ts:5:1

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { FormatInputPathObject, ParsedPath } from "./_interface.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.60.0/path/win32.ts:5:1

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.60.0/path/win32.ts:917:18

TS1371 [ERROR]: This import is never used as a value and must use 'import type' because the 'importsNotUsedAsValues' is set to 'error'.
import { FormatInputPathObject, ParsedPath } from "./_interface.ts";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/std@0.60.0/path/posix.ts:5:1

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.60.0/path/posix.ts:438:18

Found 5 errors.
```

Should be a case of upgrading to `std@0.69.0` and `media_types@v2.4.7` to fix the `URL` issues (due to breaking change in 1.2.x version of Deno) and the strict type checks introduced for `--unstable` use in Deno 1.4.x.

Result of `deno info`:

```console
├─┬ https://deno.land/x/type_is@1.0.2/mod.ts (4.99KB)
│ └─┬ https://deno.land/x/type_is@1.0.2/deps.ts (212B)
│   ├─┬ https://deno.land/x/media_types@v2.4.1/mod.ts (4.12KB)
│   │ ├── https://deno.land/x/media_types@v2.4.1/db.ts (170.17KB)
│   │ └─┬ https://deno.land/x/media_types@v2.4.1/deps.ts (144B)
│   │   └─┬ https://deno.land/std@0.60.0/path/mod.ts (717B)
│   │     ├── https://deno.land/std@0.60.0/path/_constants.ts (2.23KB)
│   │     ├─┬ https://deno.land/std@0.60.0/path/win32.ts (26.88KB)
│   │     │ ├── https://deno.land/std@0.60.0/path/_interface.ts (657B)
│   │     │ ├── https://deno.land/std@0.60.0/path/_constants.ts *
│   │     │ ├─┬ https://deno.land/std@0.60.0/path/_util.ts (3.3KB)
│   │     │ │ ├── https://deno.land/std@0.60.0/path/_interface.ts *
│   │     │ │ └── https://deno.land/std@0.60.0/path/_constants.ts *
│   │     │ └── https://deno.land/std@0.60.0/_util/assert.ts (405B)
│   │     ├─┬ https://deno.land/std@0.60.0/path/posix.ts (12.57KB)
│   │     │ ├── https://deno.land/std@0.60.0/path/_interface.ts *
│   │     │ ├── https://deno.land/std@0.60.0/path/_constants.ts *
│   │     │ └── https://deno.land/std@0.60.0/path/_util.ts *
│   │     ├─┬ https://deno.land/std@0.60.0/path/common.ts (1.14KB)
│   │     │ └─┬ https://deno.land/std@0.60.0/path/separator.ts (264B)
│   │     │   └── https://deno.land/std@0.60.0/path/_constants.ts *
│   │     ├── https://deno.land/std@0.60.0/path/separator.ts *
│   │     ├── https://deno.land/std@0.60.0/path/_interface.ts *
│   │     └─┬ https://deno.land/std@0.60.0/path/glob.ts (3.32KB)
│   │       ├── https://deno.land/std@0.60.0/path/separator.ts *
│   │       ├─┬ https://deno.land/std@0.60.0/path/_globrex.ts (7.49KB)
│   │       │ └── https://deno.land/std@0.60.0/path/_constants.ts *
│   │       ├── https://deno.land/std@0.60.0/path/mod.ts *
│   │       └── https://deno.land/std@0.60.0/_util/assert.ts *
│   ├── https://deno.land/x/content_type@1.0.1/mod.ts (3.89KB)
│   └── https://deno.land/x/media_typer@1.0.1/mod.ts (2.88KB)
```

**Comment by asos-craigmorten** [comment]
Closing as stale, and don't require as part of my projects anymore. If this is impacting others, feel free to re-open.
